version: "3.8"

networks:
  micro_network:
    name: micro_network
    external: false
    driver: bridge

services:

  rabbitmq: # login guest:guest
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq-server
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"
    tty: true
    networks:
      - micro_network
    restart: always

  redpanda:
    # NOTE: Please use the latest version here!
    image: docker.vectorized.io/vectorized/redpanda:latest
    container_name: redpanda
    ports:
      - "9092:9092"
      - "29092:29092"
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    networks:
      - micro_network
    restart: always